name: forex_imf_tes
description: Sample Front End Development test
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  google_fonts: ^5.1.0
  extended_image: ^8.0.2
  loading_animation_widget: ^1.2.0+4
  equatable: ^2.0.5
  get_storage: ^2.1.1
  intl:
  syncfusion_flutter_charts: ^22.1.36
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true